[package]
name = "threat-intel"
version.workspace = true
edition.workspace = true

[dependencies]
actix-web.workspace = true
actix-cors.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
chrono.workspace = true
dotenvy.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
sentinel-common = { path = "../common" }
